max_epoch: 10
nb_lstm_units: 50
nb_lstm_layers: 1
batchsize: 2
learning_rate: 0.001
embed_lr: 0.005
test_perc: 0.2
threshold: 0.2
embed_dim: 10
perc_sample_print: 0.000
data_name: 'test'
include_correct: False
exercise_filename: '~/sorted_data/khan_problem_token_3only_tiny'
output_sample_filename: '~/sorted_data/sample_sessions/sample_prediction_generated'
content_index_filename: 'data/exercise_index_3only'
